### ISSUE TITLE
Add an "immediate" boolean to the meta object

### ISSUE THREAD

**Issue by dispix** [ryanseddon/redux-debounced#8]
# Use case

In some situation, I want the action to be dispatched at the start of the debounce timer rather than at the end.

For example, if I want to dispatch a `USER_ACTIVE` action related to a mousemove event I need to do it at the first event instead of the last one.

See the third parameter of the following function:

``` javascript
function debounce(func, wait, immediate) {
    var timeout;
    return function() {
        var context = this, args = arguments;
        var later = function() {
            timeout = null;
            if (!immediate) func.apply(context, args);
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) func.apply(context, args);
    };
};
```

**Comment by ryanseddon** [comment]
Yeah that seems reasonable you want to do a PR for this?

**Comment by dispix** [comment]
@ryanseddon Done. Better than just and `immediate` boolean, I opted for `leading` and `trailing`, giving the option to dispatch the action at the beginning and/or the end of the debouncing.

See #10
